model:
  class_path: drumblender.tasks.DrumBlender
  init_args:
    encoder: models/embedding/eats_64.yaml
    modal_synth: drumblender.synths.ModalSynth
    modal_autoencoder: models/encoder/modal_mlp_encoder.yaml
    transient_synth: synths/transient_tcn.yaml
    noise_synth: synths/noise.yaml
    noise_autoencoder:
      class_path: drumblender.models.encoders.NoiseParameters
      init_args:
        param_shape:
          - 1
          - 189
          - 64
    loss_fn: loss/mss.yaml
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/percussion.yaml
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 200
  callbacks:
  - class_path: drumblender.callbacks.LogAudioCallback
    init_args:
      on_train: true
      on_val: true
      on_test: true
      save_audio_sr: 48000
      n_batches: 1
seed_everything: 396818285
