# Config for kick synth reconstruction using a TCN synthesis model with 300k+ params
# and a jointly learned EAT-S model used for a FiLM embedding.
# Designed to run on an A5000

model:
  class_path: kick2kick.tasks.KickSynth
  init_args:
    model: models/tcn/kicktcn_film_lrg.yaml
    loss_fn: loss/triple_loss.yaml
    embedding_model:
      class_path: kick2kick.models.components.BatchNormProjection
      init_args:
        in_features: 1880
        out_features: 64
    float32_matmul_precision: medium
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0005
    weight_decay: 0.00001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/kick_modal_mfcc.yaml
trainer:
  # devices: [0]
  # accelerator: gpu
  max_epochs: 200
  #logger: logger/wandb.yaml
  callbacks:
    class_path: pytorch_lightning.callbacks.LearningRateMonitor
seed_everything: 396818285
#ckpt_path: logs/kick2kick/vmxz43t8/checkpoints/epoch=121-step=84180.ckpt
