# Config for kick synth reconstruction using a TCN synthesis model with 100k+ params
# and a jointly learned EAT-S model used for a FiLM embedding.
# Designed to run on a small GPU (2080 Super)

model:
  class_path: drumblender.tasks.KickSynth
  init_args:
    model: models/tcn/kicktcn_film.yaml
    loss_fn: loss/triple_loss.yaml
    embedding_model: models/embedding/eats_64.yaml
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0005
    weight_decay: 0.00001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/kick_modal_params.yaml
trainer:
  # devices: [0]
  # accelerator: gpu
  max_epochs: 200
  logger: logger/wandb.yaml
  callbacks:
    class_path: pytorch_lightning.callbacks.LearningRateMonitor
seed_everything: 396818285
#ckpt_path: logs/drumblender/f274boeb/checkpoints/epoch=114-step=158585.ckpt
