# Config for an experiment overfitting a TCN to generate a kick

model:
  class_path: drumblender.tasks.KickSynth
  init_args:
    model: models/tcn/kicktcn.yaml
    loss_fn: loss/triple_loss.yaml
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/kick_single_ludwig_1mode.yaml
trainer:
  devices: [0]
  accelerator: gpu
  max_epochs: 250
  callbacks:
    - class_path: drumblender.callbacks.LogAudioCallback
      init_args:
        on_train: true
        on_val: true
        on_test: true
        save_audio_sr: 48000
        n_batches: 1
seed_everything: 396818285
#ckpt_path: lightning_logs/version_473/checkpoints/epoch=249-step=2000.ckpt
