# Config for an experiment overfitting a TCN to generate a kick with non-modal
# conditioning.

# TODO: find out if there's a way with LightningCLI/jsonargparse to compose configs in
# a way that doesn't require duplicating the entire config to override specific values.
# I suspect the answer is no, but it may be possible using the OmegaConf loader...

model:
  class_path: kick2kick.tasks.KickSynth
  init_args:
    model:
      class_path: kick2kick.models.TCN
      init_args:
        in_channels: 64
        hidden_channels: 32
        out_channels: 1
        dilation_base: 10
        num_layers: 5
        kernel_size: 3
        causal: True
        norm: instance
        activation: GELU
        film_conditioning: False
    loss_fn: loss/triple_loss.yaml
    conditioning_model: models/conditioning/fourier.yaml
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/kick_single_ludwig_1mode.yaml
trainer:
  devices: [0]
  accelerator: gpu
  max_epochs: 250
seed_everything: 396818285
#ckpt_path: lightning_logs/version_473/checkpoints/epoch=249-step=2000.ckpt
