model:
  class_path: drumblender.tasks.DrumBlender
  init_args:
    encoder: null
    modal_synth: drumblender.synths.ModalSynth
    modal_autoencoder: null
    transient_synth: null
    transient_autoencoder: null
    noise_synth: synths/noise.yaml
    noise_autoencoder: models/encoder/noise_soundstream.yaml
    noise_autoencoder_accepts_audio: true
    loss_fn: loss/mss.yaml
    transient_parallel: false
    float32_matmul_precision: medium
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/singles/tom-pop-single.yaml
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 200
  callbacks:
  - class_path: drumblender.callbacks.LogAudioCallback
    init_args:
      on_train: true
      on_val: true
      on_test: true
      save_audio_sr: 48000
      n_batches: 1
seed_everything: 396818285
