model:
  class_path: drumblender.tasks.DrumBlender
  init_args:
    modal_synth: drumblender.synths.ModalSynth
    modal_autoencoder:
      class_path: drumblender.models.encoders.ModalAmpParameters
      init_args:
        num_modes: 64
    transient_synth: synths/transient_tcn_nofilm.yaml
    noise_synth: synths/noise.yaml
    noise_autoencoder:
      class_path: drumblender.models.encoders.NoiseParameters
      init_args:
        param_shape:
          - 1
          - 189
          - 64
    loss_fn: loss/mss.yaml
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/singles/tom-pop-single.yaml
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 200
  callbacks:
  - class_path: drumblender.callbacks.LogAudioCallback
    init_args:
      on_train: true
      on_val: true
      on_test: true
      save_audio_sr: 48000
      n_batches: 1
seed_everything: 396818285
