model:
  class_path: drumblender.tasks.DrumBlender
  init_args:
    modal_synth: drumblender.synths.ModalSynth
    modal_autoencoder:
      class_path: drumblender.models.encoders.ModalAmpParameters
      init_args:
        num_modes: 64
    transient_synth:
      class_path: drumblender.synths.TransientTCN
      init_args:
        in_channels: 1
        hidden_channels: 32
        out_channels: 1
        dilation_base: 2
        dilation_blocks: 8
        num_layers: 8
        kernel_size: 13
        transient_conditioning: false
        transient_conditioning_channels: 31
    noise_synth:
      class_path: drumblender.synths.NoiseGenerator
      init_args:
        window_size: 1024
    noise_autoencoder:
      class_path: drumblender.models.encoders.NoiseParameters
      init_args:
        param_shape:
          - 1
          - 189
          - 64
    loss_fn: loss/mss.yaml
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
data: data/singles/tom-pop-single.yaml
trainer:
  devices: [0]
  accelerator: gpu
  max_epochs: 200
  callbacks:
  - class_path: drumblender.callbacks.LogAudioCallback
    init_args:
      on_train: true
      on_val: true
      on_test: true
      save_audio_sr: 48000
      n_batches: 1
seed_everything: 396818285
