name: Test Model Inference

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Model Inference
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # cache pip dependencies
          cache-dependency-path: "**/pyproject.toml" # cache dependencies based on pyproject.toml
      - name: Get models
        run: |
          git submodule update --init --recursive
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[modal]"
      - name: Run inference
        run: |
          drumblender-synth models/forum-acusticum-2023/noise_parallel_transient_params.yaml models/forum-acusticum-2023/noise_parallel_transient_params.ckpt audio/a_snare.wav snare_resynth.wav
