name: Test Modal

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    name: Python Tests with Modal
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # cache pip dependencies
          cache-dependency-path: "**/pyproject.toml" # cache dependencies based on pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev, modal]"
      - name: Disable wandb
        run: |
          wandb disabled
      - name: Test with pytest
        run: |
          pytest
