name: Test Modal

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # cache pip dependencies
          cache-dependency-path: "**/pyproject.toml" # cache dependencies based on pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev, modal]"
      - name: Disable wandb
        run: |
          wandb disabled
      - name: Test with pytest
        run: |
          pytest
